const {app,BrowserWindow,ipcMain,safeStorage,shell}=require('electron');
const path=require('path'),fs=require('fs'),os=require('os'),crypto=require('crypto');
const {spawn,execFileSync}=require('child_process');
const SUPABASE_URL='https://fqwoshdohwcbdgbdvmqc.supabase.co';
const SUPABASE_KEY='sb_publishable_XMv1L9yIinwd1KuMMa-lUQ_Yj2HZ4qc';
const LICENSE_URL=SUPABASE_URL+'/functions/v1/fire-blaze-license';
const CHECKOUT_URL=SUPABASE_URL+'/functions/v1/fire-blaze-checkout';
const CUSTOMER_URL='https://fire-blaze-site.onrender.com/cliente.html';
let win=null,auth=null;
const authFile=()=>path.join(app.getPath('userData'),'auth.bin');
const root=()=>path.join(process.env.LOCALAPPDATA||app.getPath('userData'),'FIRE BLAZE','.runtime','Mult');
const parts=v=>String(v||'0').replace(/^v/i,'').split('.').map(x=>Number(x)||0);
function cmp(a,b){const A=parts(a),B=parts(b);for(let i=0;i<Math.max(A.length,B.length);i++){const d=(A[i]||0)-(B[i]||0);if(d)return d}return 0}
function saveAuth(v){auth=v||null;if(!auth){try{fs.rmSync(authFile(),{force:true})}catch{};return}if(!safeStorage.isEncryptionAvailable())throw Error('Criptografia segura do Windows indisponível.');fs.mkdirSync(path.dirname(authFile()),{recursive:true});fs.writeFileSync(authFile(),safeStorage.encryptString(JSON.stringify(auth)))}
function loadAuth(){try{if(!fs.existsSync(authFile())||!safeStorage.isEncryptionAvailable())return null;auth=JSON.parse(safeStorage.decryptString(fs.readFileSync(authFile())));return auth}catch{return null}}
async function token(grant,body){const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type='+grant,{method:'POST',headers:{apikey:SUPABASE_KEY,'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Error(d?.error_description||d?.msg||'Falha na autenticação.');d.saved_at=Date.now();saveAuth(d);return d}
async function refresh(){if(!auth?.refresh_token)return null;try{return await token('refresh_token',{refresh_token:auth.refresh_token})}catch{saveAuth(null);return null}}
async function accessToken(){if(!auth)loadAuth();if(!auth)return '';if(Date.now()>(auth.saved_at||0)+Number(auth.expires_in||3600)*1000-60000)await refresh();return auth?.access_token||''}
async function api(url,body){let t=await accessToken();if(!t)throw Error('Faça login novamente.');let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+t},body:JSON.stringify(body||{})});let d=await r.json().catch(()=>({}));if(r.status===401){await refresh();t=auth?.access_token||'';if(t){r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+t},body:JSON.stringify(body||{})});d=await r.json().catch(()=>({}))}}if(!r.ok||d?.ok===false)throw Error(d?.error||'Erro no servidor.');return d}
async function account(){const t=await accessToken();if(!t)return {logged:false};let r=await fetch(LICENSE_URL+'?action=account',{headers:{authorization:'Bearer '+t}});let d=await r.json().catch(()=>({}));if(r.status===401){if(await refresh())return account();return {logged:false}}if(!r.ok)return {logged:true,ok:false,error:d?.error||'Erro ao consultar assinatura.'};return {logged:true,...d}}
function findExe(dir){try{if(!fs.existsSync(dir))return '';const direct=path.join(dir,'FIRE BLAZE Mult.exe');if(fs.existsSync(direct))return direct;for(const e of fs.readdirSync(dir,{withFileTypes:true}))if(e.isDirectory()){const f=findExe(path.join(dir,e.name));if(f)return f}}catch{}return ''}
function candidates(){try{if(!fs.existsSync(root()))return [];const a=[];for(const e of fs.readdirSync(root(),{withFileTypes:true})){if(!e.isDirectory())continue;const dir=path.join(root(),e.name),exe=findExe(dir);if(exe)a.push({version:String(e.name).replace(/^v/i,''),exe,dir})}a.sort((x,y)=>cmp(y.version,x.version));return a}catch{return []}}
function installedVersion(){return candidates()[0]?.version||''}
async function download(url,dest){const r=await fetch(url,{redirect:'follow'});if(!r.ok)throw Error('Falha ao baixar o Mult ('+r.status+').');fs.mkdirSync(path.dirname(dest),{recursive:true});const total=Number(r.headers.get('content-length')||0),fh=fs.openSync(dest,'w');let n=0;try{const rd=r.body.getReader();while(true){const q=await rd.read();if(q.done)break;fs.writeSync(fh,Buffer.from(q.value));n+=q.value.length;win?.webContents.send('v2:progress',{stage:'download',progress:total?Math.round(n*100/total):0})}}finally{fs.closeSync(fh)}}
async function ensureInstalled(a){const latest=a?.latest_version;if(!latest?.version)throw Error('Nenhuma versão do Mult publicada.');const v=String(latest.version).replace(/^v/i,''),best=candidates()[0];if(best&&cmp(best.version,v)>=0)return {version:best.version,path:best.exe};const target=path.join(root(),v),existing=findExe(target);if(existing)return {version:v,path:existing};if(!latest.download_url)throw Error('Pacote do Mult não publicado.');const temp=path.join(app.getPath('temp'),'FIRE-BLAZE-V2'),zip=path.join(temp,'multi-'+v+'.zip');fs.rmSync(temp,{recursive:true,force:true});fs.mkdirSync(temp,{recursive:true});await download(latest.download_url,zip);if(latest.sha256){const h=crypto.createHash('sha256').update(fs.readFileSync(zip)).digest('hex');if(h.toLowerCase()!==String(latest.sha256).toLowerCase())throw Error('Falha de integridade do download.')}fs.rmSync(target,{recursive:true,force:true});fs.mkdirSync(target,{recursive:true});win?.webContents.send('v2:progress',{stage:'install',progress:0});execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',"Expand-Archive -LiteralPath '"+zip.replace(/'/g,"''")+"' -DestinationPath '"+target.replace(/'/g,"''")+"' -Force"],{windowsHide:true,timeout:180000});const exe=findExe(target);if(!exe)throw Error('FIRE BLAZE Mult.exe não encontrado no pacote.');fs.rmSync(zip,{force:true});win?.webContents.send('v2:progress',{stage:'done',progress:100});return {version:v,path:exe}}
function deviceHash(){let m='';try{m=String(execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command','(Get-CimInstance Win32_ComputerSystemProduct).UUID'],{encoding:'utf8',windowsHide:true,timeout:5000})||'').trim()}catch{}return crypto.createHash('sha256').update([m,os.hostname(),process.platform,process.arch].join('|')).digest('hex')}
async function state(){return {account:await account(),installed_version:installedVersion(),device_name:os.hostname(),launcher_version:app.getVersion()}}
ipcMain.handle('v2:state',state);
ipcMain.handle('v2:login',async(_e,e,p)=>{await token('password',{email:String(e||'').trim(),password:String(p||'')});return state()});
ipcMain.handle('v2:logout',async()=>{saveAuth(null);return {ok:true}});
ipcMain.handle('v2:install',async()=>{const a=await account();if(!a.logged)throw Error('Faça login.');if(!a.active)throw Error(a?.subscription?.access_kind==='trial'?'Seu teste terminou. Assine para liberar o Multi.':'Sua assinatura está inativa.');const i=await ensureInstalled(a);return {ok:true,installed_version:i.version}});
ipcMain.handle('v2:launch',async()=>{const a=await account();if(!a.logged)throw Error('Faça login.');if(!a.active)throw Error(a?.subscription?.access_kind==='trial'?'Seu teste terminou. Assine para liberar o Multi.':'Sua assinatura está inativa.');const i=await ensureInstalled(a);const t=await api(LICENSE_URL+'?action=issue_ticket',{device_hash:deviceHash(),device_name:os.hostname()});win?.hide();const c=spawn(i.path,['--fire-blaze-ticket='+t.ticket],{cwd:path.dirname(i.path),stdio:'ignore',windowsHide:false});c.on('error',()=>{win?.show();win?.focus()});c.on('exit',()=>setTimeout(()=>{win?.show();win?.focus()},3000));return {ok:true,installed_version:i.version}});
ipcMain.handle('v2:renew',async(_e,m)=>{const d=await api(CHECKOUT_URL,{method:String(m||'pix')});if(!d.checkout_url)throw Error('Checkout não retornado.');await shell.openExternal(d.checkout_url);return {ok:true}});
ipcMain.handle('v2:customer',async()=>{await shell.openExternal(CUSTOMER_URL);return true});
function create(){win=new BrowserWindow({width:1060,height:720,minWidth:900,minHeight:620,backgroundColor:'#07090d',title:'FIRE BLAZE Launcher V2',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.loadFile('index.html')}
if(!app.requestSingleInstanceLock())app.quit();else{app.on('second-instance',()=>{if(win){win.show();win.focus()}});app.whenReady().then(()=>{loadAuth();create()});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()})}
